hiddenimports = [
    "pyaudio",
    "pyperclip",
    "comtypes",
    "sherpa_onnx",
    "soundfile",
]


a = Analysis(
    ["voice_backend.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "torch",
        "sklearn",
        "scipy",
        "pandas",
        "matplotlib",
        "tensorflow",
        "transformers",
        "huggingface_hub",
        "tensorboard",
        "IPython",
        "jupyter",
        "pytest",
        "funasr",
        "modelscope",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="yanqi-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=["app.ico"],
)
